name: End to End Tests

on:
  deployment_status:

jobs:
  run-tests:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm i --frozen-lockfile

      - run: pnpm dlx playwright install --with-deps

      - run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
